defmodule GitDiff.Chunk do
  @moduledoc """
  Every patch generated by a 'git diff' command contains one or more chunks
  """
  
  @doc """
  Defines the Chunk struct.
  
  * :from_start_line - The line at which this chunk began preimage.
  * :to_start_line - The line at which this chunk began postimages.
  * :from_num_lines - The number of lines in the file preimage.
  * :to_num_lines - The number of lines in the file postimages.
  * :header - The header indicating the format and the file names.
  * :lines - The lines of text contained within this chunk of changes. See `GitDiff.Line`.
  * :context - The extracted context from the header if there is one. A blank string otherwise.
  """
  defstruct from_start_line: nil, from_num_lines: nil, to_start_line: nil, to_num_lines: nil, header: nil, lines: [], context: nil
end